### ISSUE TITLE
Installs Dev-Version with Dev options enabled, even if Non-Dev was installed before

### ISSUE THREAD

**Issue by Natanji** [astronautlevel2/StarUpdater#4]
I had the following problem.
I installed Luma3DS 5.4 for the very first time a few days ago. Normal version, not dev.
Everything was working fine. Then I used the Luma3DS-updater (because the installation guide says I should, even though I already had 5.4) and suddenly I couldn't use the eShop anymore.

Then I found out that the Updater had a) installed the dev version of Luma3DS, and b) enabled the developer feature in the options (that were not even available previously, since the non-dev version does not have it). That could probably confuse quite a few people. Other people had this problem as well, see: https://www.reddit.com/r/3dshacks/comments/4h79o5/psa_lumaupdater_installs_dev_version_and_enables/

**Comment by astronautlevel2** [comment]
This was a problem with @Hamcha's updater, not mine. Here's the repo for his project: https://github.com/Hamcha/lumaupdate

IIRC he fixed it on the last version, so don't go opening an issue for it :P 

If it turns out that my updater somehow managed to install the dev version (which should be impossible given that it uses my compiles from the main branch) just post a comment and I'll re-open the issue.

**Comment by Natanji** [comment]
Sorry for mistaking the project, the names are just so similar! ^^

Am 04.05.2016 00:40 schrieb Alex Taber notifications@github.com:

This was a problem with @Hamcha's updater, not mine. Here's the repo for his project: https://github.com/Hamcha/lumaupdate

IIRC he fixed it on the last version, so don't go opening an issue for it :P 

If it turns out that my updater somehow managed to install the dev version (which should be impossible given that it uses my compiles from the main branch) just post a comment and I'll re-open the issue.

**Comment by astronautlevel2** [comment]
Don't worry about it, there's a reason I opened #5
