### ISSUE TITLE
Support updating the payload in CTRNAND

### ISSUE THREAD

**Issue by Margen67** [astronautlevel2/StarUpdater#52]
You can use Luma without an SD now. StarUpdater should support this.

**Comment by astronautlevel2** [comment]
1. StarUpdater isn't being supported anymore because school takes up too much of my time and I have no more motivation to work on this
2. You can't write directly to CTRNAND from arm11.

**Comment by ihaveamac** [comment]
> You can't write directly to CTRNAND from arm11.

from lpp-3ds at least. FBI can do this.

**Comment by astronautlevel2** [comment]
I was under the impression that FBI could only read CTRNAND, not write to it. Then again, I haven't been following the scene in forever, so

EDIT: Nope, looks like I was wrong. Either way, since it's not possible from lpp-3ds and I'm not going to be rewriting this the issue is going to remain closed.
